In [ ]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

# 1 Carregando os dados

In [ ]:
path = '/content/drive/MyDrive/Sistemas_de_Informação/Sistemas inteligentes/RESOLUÇÕES/atv_02'
dataset = 'casoCovidPI.csv'

In [ ]:
os.chdir(path)

In [ ]:
os.getcwd()

'/content/drive/MyDrive/Sistemas_de_Informação/Sistemas inteligentes/RESOLUÇÕES/atv_02'

In [ ]:
dfCovid = pd.read_csv(dataset)
dfCovid

,date,state,city,place_type,confirmed,deaths,order_for_place,is_last,estimated_population_2019,estimated_population,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,2022-03-26,PI,Acauã,city,228,2,658,True,7084.0,7102.0,2200053.0,3210.36328,0.0088
1,2022-03-26,PI,Agricolândia,city,829,10,650,True,5139.0,5131.0,2200103.0,16156.69460,0.0121
2,2022-03-26,PI,Alagoinha do Piauí,city,402,13,664,True,7651.0,7665.0,2200251.0,5244.61840,0.0323
3,2022-03-26,PI,Alegrete do Piauí,city,553,9,646,True,4915.0,4918.0,2200277.0,11244.40830,0.0163
4,2022-03-26,PI,Alto Longá,city,858,15,680,True,14304.0,14339.0,2200301.0,5983.68087,0.0175
...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,2022-03-26,PI,Vila Nova do Piauí,city,349,3,689,True,2971.0,2952.0,2211605.0,11822.49322,0.0086
220,2022-03-26,PI,Várzea Branca,city,204,12,666,True,4947.0,4938.0,2211357.0,4131.22722,0.0588
221,2022-03-26,PI,Várzea Grande,city,561,1,697,True,4391.0,4386.0,2211407.0,12790.69767,0.0018
222,2022-03-26,PI,Wall Ferraz,city,335,3,642,True,4462.0,4471.0,2211704.0,7492.73093,0.0090
223,2022-03-26,PI,Água Branca,city,1702,77,699,True,17411.0,17470.0,2200202.0,9742.41557,0.0452

# 2 Verificando se há dados nulos

In [ ]:
dfCovid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   date                            224 non-null    object
 1   state                           224 non-null    object
 2   city                            224 non-null    object
 3   place_type                      224 non-null    object
 4   confirmed                       224 non-null    int64
 5   deaths                          224 non-null    int64
 6   order_for_place                 224 non-null    int64
 7   is_last                         224 non-null    bool
 8   estimated_population_2019       224 non-null    float64
 9   estimated_population            224 non-null    float64
 10  city_ibge_code                  224 non-null    float64
 11  confirmed_per_100k_inhabitants  224 non-null    float64
 12  death_rate                      224 non-null    float64
dtypes: bool(1), float64(5), int64(3), object(4)
memory usage: 21.3+ KB

In [ ]:
dfCovid.isnull().sum()

date                              0
state                             0
city                              0
place_type                        0
confirmed                         0
deaths                            0
order_for_place                   0
is_last                           0
estimated_population_2019         0
estimated_population              0
city_ibge_code                    0
confirmed_per_100k_inhabitants    0
death_rate                        0
dtype: int64

# Tratando os dados categóricos

In [ ]:
dfCovid2 = dfCovid.drop(['state', 'place_type', 'is_last', 'date', 'city'],axis=1)
dfCovid2

,confirmed,deaths,order_for_place,estimated_population_2019,estimated_population,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,228,2,658,7084.0,7102.0,2200053.0,3210.36328,0.0088
1,829,10,650,5139.0,5131.0,2200103.0,16156.69460,0.0121
2,402,13,664,7651.0,7665.0,2200251.0,5244.61840,0.0323
3,553,9,646,4915.0,4918.0,2200277.0,11244.40830,0.0163
4,858,15,680,14304.0,14339.0,2200301.0,5983.68087,0.0175
...,...,...,...,...,...,...,...,...
219,349,3,689,2971.0,2952.0,2211605.0,11822.49322,0.0086
220,204,12,666,4947.0,4938.0,2211357.0,4131.22722,0.0588
221,561,1,697,4391.0,4386.0,2211407.0,12790.69767,0.0018
222,335,3,642,4462.0,4471.0,2211704.0,7492.73093,0.0090
223,1702,77,699,17411.0,17470.0,2200202.0,9742.41557,0.0452

In [ ]:
dfCovid2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   confirmed                       224 non-null    int64
 1   deaths                          224 non-null    int64
 2   order_for_place                 224 non-null    int64
 3   estimated_population_2019       224 non-null    float64
 4   estimated_population            224 non-null    float64
 5   city_ibge_code                  224 non-null    float64
 6   confirmed_per_100k_inhabitants  224 non-null    float64
 7   death_rate                      224 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 14.1 KB

# 3 Divisão treino/teste

## 3.1 Definindo x e y

In [ ]:
x = dfCovid2.drop('deaths',axis=1)
x

,confirmed,order_for_place,estimated_population_2019,estimated_population,city_ibge_code,confirmed_per_100k_inhabitants,death_rate
0,228,658,7084.0,7102.0,2200053.0,3210.36328,0.0088
1,829,650,5139.0,5131.0,2200103.0,16156.69460,0.0121
2,402,664,7651.0,7665.0,2200251.0,5244.61840,0.0323
3,553,646,4915.0,4918.0,2200277.0,11244.40830,0.0163
4,858,680,14304.0,14339.0,2200301.0,5983.68087,0.0175
...,...,...,...,...,...,...,...
219,349,689,2971.0,2952.0,2211605.0,11822.49322,0.0086
220,204,666,4947.0,4938.0,2211357.0,4131.22722,0.0588
221,561,697,4391.0,4386.0,2211407.0,12790.69767,0.0018
222,335,642,4462.0,4471.0,2211704.0,7492.73093,0.0090
223,1702,699,17411.0,17470.0,2200202.0,9742.41557,0.0452

In [ ]:
y = dfCovid2['deaths']
y

0       2
1      10
2      13
3       9
4      15
       ..
219     3
220    12
221     1
222     3
223    77
Name: deaths, Length: 224, dtype: int64

In [ ]:
print(x.shape)
print(y.shape)

(224, 7)
(224,)

## 3.2 Separando os dados

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
print('#Conjunto de treino:')
print(x_train.shape)
print(y_train.shape)
print('#Conjunto de treino:')
print(x_test.shape)
print(y_test.shape)

#Conjunto de treino:
(179, 7)
(179,)
#Conjunto de treino:
(45, 7)
(45,)


## 3.3 Padronização dos dados (Feature Scaling)

In [ ]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## 3.4 Salvando os dados

In [ ]:
pickle.dump(x_train, open('X_train.pickle', 'wb'))
pickle.dump(x_test, open('X_test.pickle', 'wb'))
pickle.dump(y_train, open('y_train.pickle', 'wb'))
pickle.dump(y_test, open('y_test.pickle', 'wb'))

In [ ]:
def read_pickle(name):
    with (open(name, 'rb')) as openfile:
        while True:
            try:
                one_instance = pickle.load(openfile)
            except EOFError:
                break
    one_instance = np.asanyarray(one_instance)
    return one_instance

In [ ]:
x_train = read_pickle('X_train.pickle')
x_test = read_pickle('X_test.pickle')
y_train = read_pickle('y_train.pickle')
y_test = read_pickle('y_test.pickle')

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(179, 7)
(179,)
(45, 7)
(45,)